spring:
  application:
    name: bff-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/omni-market}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  otlp:
    metrics:
      export:
        url: ${OTEL_COLLECTOR_URL:http://localhost:8000/otel}/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_URL:http://localhost:8000/otel}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTEL_COLLECTOR_URL:http://localhost:8000/otel}/v1/logs
